name: viscanvas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  universal_io: ^2.2.2
  provider: ^6.1.2
  path: ^1.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.15.2                    # Advanced integration testing with native APIs
  mocktail: ^1.0.0                   # Null-safe mocking
  golden_toolkit: ^0.15.0            # Visual regression testing
  fake_async: ^1.3.0                 # Time-based testing
  test: ^1.24.0                      # Property-based testing support
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
